### PR TITLE
Add a checbox preferences to hide the chat ghost textarea

### PR DESCRIPTION
**Pull request by p4535992**
Add a checbox preferences to hide the chat ghost textarea because some people don't want that

### CODE REVIEW

**Comment by ernieayala** [comment]
Hey, thanks for for the PR.
Can you explain to me what "chat ghost textarea" is? Like a screenshot or something

**Comment by p4535992** [comment]
Hey, ty agan for this beautiful UI, here the screenshoots.

The 'chat ghost textarea' is the textarea on the right of the standard chat textarea.

Before (checkbox to false):

chatghostarea_on

After  (checkbox to true):

chatghostarea_on

It's little thing, personally i prefer the after style, but i'm not sure about the others so i made a module settings for manage that.

If you have in mind some better style, you are more than welcome.

**NOTE:**
I added a Fix for the  module "Illandril's Chat Enhancements" and a little css for reduce the padding on the form group of the token sheet and manage different combination of modules (perfect vision, conditional visibility, ecc.)

**Comment by ernieayala** [comment]
Haven't forgot about this. I've just been down with the flu.

**Comment by p4535992** [comment]
I think this pull is deprecated.

**Pull request closed without merging**
